subClass_0(0, 1).
class_0(2).
class_0(0).
class_0(1).
inst_0(X, X) :- nom_0(X).
self_0(X, V) :- nom_0(X), triple_0(X, V, X).
inst_0(X, Z) :- top_0(Z), inst_0(X, Z1).
inst_0(X, Y) :- bot_0(Z), inst_0(U, Z), inst_0(X, Z1), cls_0(Y).
inst_0(X, Z) :- subClass_0(Y, Z), inst_0(X, Y).
inst_0(X, Z) :- subConj_0(Y1, Y2, Z), inst_0(X, Y1), inst_0(X, Y2).
inst_0(X, Z) :- subEx_0(V, Y, Z), triple_0(X, V, X1), inst_0(X1, Y).
inst_0(X, Z) :- subEx_0(V, Y, Z), self_0(X, V), inst_0(X, Y).
triple_0(X, V, X1) :- supEx_0(Y, V, Z, X1), inst_0(X, Y).
inst_0(X1, Z) :- supEx_0(Y, V, Z, X1), inst_0(X, Y).
inst_0(X, Z) :- subSelf_0(V, Z), self_0(X, V).
self_0(X, V) :- supSelf_0(Y, V), inst_0(X, Y).
triple_0(X, W, X1) :- subRole_0(V, W), triple_0(X, V, X1).
self_0(X, W) :- subRole_0(V, W), self_0(X, V).
triple_0(X, W, X11) :- subRChain_0(U, V, W), triple_0(X, U, X1), triple_0(X1, V, X11).
triple_0(X, W, X1) :- subRChain_0(U, V, W), self_0(X, U), triple_0(X, V, X1).
triple_0(X, W, X1) :- subRChain_0(U, V, W), triple_0(X, U, X1), self_0(X1, V).
triple_0(X, W, X) :- subRChain_0(U, V, W), self_0(X, U), self_0(X, V).
triple_0(X, W, X1) :- subRConj_0(V1, V2, W), triple_0(X, V1, X1), triple_0(X, V2, X1).
self_0(X, W) :- subRConj_0(V1, V2, W), self_0(X, V1), self_0(X, V2).
triple_0(X, W, X1) :- subProd_0(Y1, Y2, W), inst_0(X, Y1), inst_0(X1, Y2).
self_0(X, W) :- subProd_0(Y1, Y2, W), inst_0(X, Y1), inst_0(X, Y2).
inst_0(X, Z1) :- supProd_0(V, Z1, Z2), triple_0(X, V, X1).
inst_0(X, Z1) :- supProd_0(V, Z1, Z2), self_0(X, V).
inst_0(X1, Z2) :- supProd_0(V, Z1, Z2), triple_0(X, V, X1).
inst_0(X, Z2) :- supProd_0(V, Z1, Z2), self_0(X, V).
inst_0(Y, Z) :- inst_0(X, Y), nom_0(Y), inst_0(X, Z).
inst_0(X, Z) :- inst_0(X, Y), nom_0(Y), inst_0(Y, Z).
triple_0(Z, U, Y) :- inst_0(X, Y), nom_0(Y), triple_0(Z, U, X).
subClass_1(0, 1).
class_1(2).
class_1(0).
class_1(1).
inst_1(X, X) :- nom_1(X).
self_1(X, V) :- nom_1(X), triple_1(X, V, X).
inst_1(X, Z) :- top_1(Z), inst_1(X, Z1).
inst_1(X, Y) :- bot_1(Z), inst_1(U, Z), inst_1(X, Z1), cls_1(Y).
inst_1(X, Z) :- subClass_1(Y, Z), inst_1(X, Y).
inst_1(X, Z) :- subConj_1(Y1, Y2, Z), inst_1(X, Y1), inst_1(X, Y2).
inst_1(X, Z) :- subEx_1(V, Y, Z), triple_1(X, V, X1), inst_1(X1, Y).
inst_1(X, Z) :- subEx_1(V, Y, Z), self_1(X, V), inst_1(X, Y).
triple_1(X, V, X1) :- supEx_1(Y, V, Z, X1), inst_1(X, Y).
inst_1(X1, Z) :- supEx_1(Y, V, Z, X1), inst_1(X, Y).
inst_1(X, Z) :- subSelf_1(V, Z), self_1(X, V).
self_1(X, V) :- supSelf_1(Y, V), inst_1(X, Y).
triple_1(X, W, X1) :- subRole_1(V, W), triple_1(X, V, X1).
self_1(X, W) :- subRole_1(V, W), self_1(X, V).
triple_1(X, W, X11) :- subRChain_1(U, V, W), triple_1(X, U, X1), triple_1(X1, V, X11).
triple_1(X, W, X1) :- subRChain_1(U, V, W), self_1(X, U), triple_1(X, V, X1).
triple_1(X, W, X1) :- subRChain_1(U, V, W), triple_1(X, U, X1), self_1(X1, V).
triple_1(X, W, X) :- subRChain_1(U, V, W), self_1(X, U), self_1(X, V).
triple_1(X, W, X1) :- subRConj_1(V1, V2, W), triple_1(X, V1, X1), triple_1(X, V2, X1).
self_1(X, W) :- subRConj_1(V1, V2, W), self_1(X, V1), self_1(X, V2).
triple_1(X, W, X1) :- subProd_1(Y1, Y2, W), inst_1(X, Y1), inst_1(X1, Y2).
self_1(X, W) :- subProd_1(Y1, Y2, W), inst_1(X, Y1), inst_1(X, Y2).
inst_1(X, Z1) :- supProd_1(V, Z1, Z2), triple_1(X, V, X1).
inst_1(X, Z1) :- supProd_1(V, Z1, Z2), self_1(X, V).
inst_1(X1, Z2) :- supProd_1(V, Z1, Z2), triple_1(X, V, X1).
inst_1(X, Z2) :- supProd_1(V, Z1, Z2), self_1(X, V).
inst_1(Y, Z) :- inst_1(X, Y), nom_1(Y), inst_1(X, Z).
inst_1(X, Z) :- inst_1(X, Y), nom_1(Y), inst_1(Y, Z).
triple_1(Z, U, Y) :- inst_1(X, Y), nom_1(Y), triple_1(Z, U, X).
inst_0(X, 0) :- p(X).
inst_1(X, 0) :- s(X).
dl_ATOM_1_1(X) :- inst_1(X, 1).
dl_ATOM_1_0(X) :- inst_0(X, 1).
p(a).
s(a).
s(b).
q :- dl_ATOM_1_1(a), not dl_ATOM_1_0(b).