#!/bin/bash

if [ "${DREW_HOME}" = "" ]
then
  echo "Please set DREW_HOME by \`export DREW_HOME=/path/to/drew\`"
  exit 1
fi

drew_jar=$(ls $DREW_HOME/lib/drew-*.jar)

JVM_ARGS="-DentityExpansionLimit=128000"

exec java ${JVM_ARGS} -jar ${drew_jar} "$@"

