#!/bin/bash

# <http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in>

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

DREW_HOME="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

drew_jar=$(ls $DREW_HOME/lib/drew-*.jar)

JVM_ARGS="-DentityExpansionLimit=128000"

exec java ${JVM_ARGS} -jar ${drew_jar} "$@"

