/* Generated By:JavaCC: Do not edit this line. DLProgramParserConstants.java */
package org.semanticweb.drew.dlprogram.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DLProgramParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAF = 6;
  /** RegularExpression Id. */
  int TRUE = 7;
  /** RegularExpression Id. */
  int NAMESPACE = 8;
  /** RegularExpression Id. */
  int CONJUNCTION = 9;
  /** RegularExpression Id. */
  int IMPLY = 10;
  /** RegularExpression Id. */
  int COLON = 11;
  /** RegularExpression Id. */
  int ENDOFSTATEMENT = 12;
  /** RegularExpression Id. */
  int COMPARISON = 13;
  /** RegularExpression Id. */
  int DL_ATOM = 14;
  /** RegularExpression Id. */
  int LEFT_SQUARE_BRACKET = 15;
  /** RegularExpression Id. */
  int RIGHT_SQUARE_BRACKET = 16;
  /** RegularExpression Id. */
  int HASH_LEADING_ID = 17;
  /** RegularExpression Id. */
  int LOWER_LEADING_ID = 18;
  /** RegularExpression Id. */
  int UPPER_LEADING_ID = 19;
  /** RegularExpression Id. */
  int INTEGER = 20;
  /** RegularExpression Id. */
  int DOUBLE = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int PLUS = 23;
  /** RegularExpression Id. */
  int MINUS = 24;
  /** RegularExpression Id. */
  int TIMES = 25;
  /** RegularExpression Id. */
  int DIVIDE = 26;
  /** RegularExpression Id. */
  int LEFTBRACKET = 27;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 28;
  /** RegularExpression Id. */
  int UPLUS = 29;
  /** RegularExpression Id. */
  int UMINUS = 30;
  /** RegularExpression Id. */
  int CAPMINUS = 31;
  /** RegularExpression Id. */
  int DLPREDICATE = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"not\"",
    "\"True\"",
    "\"#namespace\"",
    "\",\"",
    "\":-\"",
    "\":\"",
    "\".\"",
    "<COMPARISON>",
    "\"DL\"",
    "\"[\"",
    "\"]\"",
    "<HASH_LEADING_ID>",
    "<LOWER_LEADING_ID>",
    "<UPPER_LEADING_ID>",
    "<INTEGER>",
    "<DOUBLE>",
    "<STRING>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"+=\"",
    "\"-=\"",
    "\"~=\"",
    "<DLPREDICATE>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"&\"",
  };

}
